### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by Pi-George** [Jocoon/php-parquet#5] opened 2021-03-23 11:37 UTC

**Comment by KevinVonJocoon** [comment] 2021-03-23 11:55
Hello there,
though no text provided, I assume you're not able to install this package in a PHP8 environment using regular composer commands.

**PHP 8 is supported** (see this project's composer.json) and also tested in the PHPUnit tests.
It is a limitation of the package `apache/thrift` not supporting PHP 8 officially, leading to a failed install try (see [https://packagist.org/packages/apache/thrift](https://packagist.org/packages/apache/thrift))

You might bypass this restriction by adding `--ignore-platform-reqs` to your composer install/update command (ignoring every other constraint also in extensions, too) - if you need it more specific, you might add `--ignore-platform-req php` instead to just skip the PHP version check (see [https://getcomposer.org/doc/03-cli.md](https://getcomposer.org/doc/03-cli.md).

Please close this issue if this answers your question.

**Comment by Pi-George** [comment] 2021-03-23 14:34
Hi, so yeah you guessed correctly there. Sorry I should've included the below in my description. I don't really want to be using --ignore-platform-req php as I'm trying to properly upgrade to php 8 rather than hack around libraries that don't support it.

```
Problem 1
    - apache/thrift v0.13.0 requires php ^5.5 || ^7.0 -> your php version (8.0.3) does not satisfy that requirement.
    - jocoon/parquet v0.4.2 requires apache/thrift ^0.13.0 -> satisfiable by apache/thrift[v0.13.0].
    - Root composer.json requires jocoon/parquet 0.4.2 -> satisfiable by jocoon/parquet[v0.4.2].
```

**Comment by KevinVonJocoon** [comment] 2021-03-23 14:56
Sadly, this won't be possible unless _they_ (Apache/the maintainers) update their package accordingly. Due to this fact, it is neither caused by nor fixable in php-parquet and therefore I'm closing this issue.

**Closed as completed by KevinVonJocoon** 2021-03-23 14:56 UTC

**Comment by KevinVonJocoon** [comment] 2021-04-29 10:29
@Pi-George FYI: the latest v0.5.0 of php-parquet fixes this circumstance by moving to an alternative to `apache/thrift` (namely `packaged/thrift`), which is also slightly better in terms of bulkiness.

**Comment by Pi-George** [comment] 2021-04-30 14:51
@KevinVonJocoon thanks, this will allow me to move away from the fork I'm currently using
